# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.CharField(default=45, max_length=10000),
            preserve_default=False,
        ),
    ]
